import Playlist from "@/src/models/Playlist";
import { ApiHelper } from "@/src/utils/axios";

/**
 * Creates a new playlist for a user.
 * Validates required fields before sending the request.
 * @param playlist Playlist object containing title, privacy status, and user ID
 * @returns Operation result with success status and message
 */
export async function createPlaylist(playlist: Playlist) {
	try {
		if (!playlist.title) {
			return {
				success: false,
				message: "Le titre de la playlist est requis",
				element: "title"
			};
		}

		if (playlist.is_private === undefined || playlist.is_private === null) {
			return {
				success: false,
				message: "Le statut de confidentialité est requis",
				element: "is_private"
			};
		}

		if (!playlist.user_id) {
			return {
				success: false,
				message: "L'identifiant de l'utilisateur est requis",
				element: "userId"
			};
		}

		// Send POST request to create a new playlist
		const result = await ApiHelper.post("/playlists/", {
			id: "", // Usually generated by backend
			user_id: playlist.user_id,
			title: playlist.title,
			created_at: new Date().toISOString(),
			is_private: playlist.is_private
		});

		// Return success or error message based on API response
		if (result.success) {
			return {
				success: true,
				message: "Playlist créée avec succès"
			};
		} else {
			return {
				success: false,
				message:
					result.data || "Erreur lors de la création de la playlist"
			};
		}
	} catch (error) {
		return {
			success: false,
			// @ts-ignore
			message: error.detail || "Une erreur est survenue"
		};
	}
}

/**
 * Updates an existing playlist.
 * Checks for restricted playlist names.
 * @param playlist Playlist object with updated data (must include id)
 * @returns Operation result with success status and message
 */
export async function updatePlaylist(playlist: Playlist) {
	if (!playlist.id) {
		return {
			success: false,
			message: "L'identifiant de la playlist est requis",
			element: "id"
		};
	}

	try {
		// Prevent certain reserved playlist names
		const restrictedNames = ["watchlist", "historique", "favoris"];
		const toLowerCaseTitle = playlist.title.toLowerCase();
		if (restrictedNames.includes(toLowerCaseTitle)) {
			return {
				success: false,
				message: "Veuillez choisir un autre nom de playlist",
				element: "title"
			};
		}

		// Send PUT request to update playlist
		const result = await ApiHelper.put(`/playlists/${playlist.id}`, {
			id: playlist.id,
			user_id: playlist.user_id,
			title: playlist.title,
			is_private: playlist.is_private
		});

		// Return success or error message based on API response
		if (result.success) {
			return {
				success: true,
				message: "Playlist mise à jour avec succès"
			};
		} else {
			return {
				success: false,
				message:
					result.data ||
					"Erreur lors de la mise à jour de la playlist"
			};
		}
	} catch (error) {
		const err = error as any;
		console.error("Error during updatePlaylist:", err);
		return {
			success: false,
			message:
				err.message || "Erreur lors de la mise à jour de la playlist"
		};
	}
}

/**
 * Deletes a playlist by its ID.
 * @param playlistId Playlist identifier
 * @returns Operation result with success status and message
 */
export async function deletePlaylist(playlistId: string) {
	if (!playlistId || typeof playlistId !== "string") {
		return {
			success: false,
			message: "ID de la playlist invalide"
		};
	}
	try {
		const stringPlaylistId = String(playlistId);
		const result = await ApiHelper.delete(`/playlists/${stringPlaylistId}`);
		if (result.success) {
			return {
				success: true,
				message: "Playlist supprimée avec succès"
			};
		} else {
			return {
				success: false,
				message:
					result.data ||
					"Erreur lors de la suppression de la playlist"
			};
		}
	} catch (error) {
		const err = error as any;
		console.error("Error during deletePlaylist:", err);
		return {
			success: false,
			message:
				err.message || "Erreur lors de la suppression de la playlist"
		};
	}
}

/**
 * Retrieves all playlists for a given user.
 * @param userId User identifier
 * @returns Object with success status and list of playlists or error message
 */
export async function getUserPlaylists(userId: string) {
	if (!userId || typeof userId !== "string") {
		return {
			success: false,
			message: "ID utilisateur invalide"
		};
	}

	try {
		const stringUserId = String(userId);
		const result = await ApiHelper.get(`/playlists/user/${stringUserId}`);
		return {
			success: true,
			data: result.data
		};
	} catch (error) {
		console.error(
			"Error in getUserPlaylists:",
			(error as any).response?.data || (error as any).message
		);
		return {
			success: false,
			message:
				(error as any).message ||
				"Erreur lors de la récupération des playlists"
		};
	}
}

/**
 * Adds a media item (movie, show, etc.) to a playlist.
 * @param playlistId Playlist identifier
 * @param mediaId Media item identifier
 * @returns Operation result with success status and message
 */
export async function addMediaToPlaylist(playlistId: string, mediaId: number) {
	if (!playlistId || typeof playlistId !== "string") {
		return {
			success: false,
			message: "ID de la playlist invalide"
		};
	}

	if (!mediaId || typeof mediaId !== "number") {
		return {
			success: false,
			message: "ID du média invalide"
		};
	}

	try {
		const result = await ApiHelper.post(
			`/playlists/${playlistId}/media/${mediaId}`,
			{
				playlist_id: playlistId,
				media_id: mediaId
			}
		);

		if (result && result.success) {
			return {
				success: true,
				message: "Média ajouté à la playlist avec succès"
			};
		} else {
			return {
				success: false,
				message:
					result?.data?.detail ||
					"Film déjà existant dans la playlist"
			};
		}
	} catch (error: any) {
		console.error("Error in addMediaToPlaylist:", error);
		return {
			success: false,
			message:
				error?.response?.data?.detail ||
				error.message ||
				"Erreur inconnue lors de l'ajout du média"
		};
	}
}

/**
 * Retrieves all media items in a playlist.
 * @param playlistId Playlist identifier
 * @returns Object with success status and list of media items or error message
 */
export async function getMediaInPlaylist(playlistId: string) {
	if (!playlistId || typeof playlistId !== "string") {
		return {
			success: false,
			message: "ID de la playlist invalide"
		};
	}

	try {
		const stringPlaylistId = String(playlistId);
		const result = await ApiHelper.get(
			`/playlists/${stringPlaylistId}/media_list`
		);
		return {
			success: true,
			data: Array.isArray(result.data) ? result.data : []
		};
	} catch (error) {
		console.error(
			"Error in getMediaInPlaylist:",
			(error as any).response?.data ||
				(error as any).message ||
				"Unknown error"
		);
		return {
			success: false,
			message:
				(error as any).message ||
				"Erreur lors de la récupération des médias de la playlist"
		};
	}
}

/**
 * Retrieves a playlist by its ID.
 * @param playlistId Playlist identifier
 * @returns Object with success status and playlist data or error message
 */
export async function getPlaylistById(playlistId: string) {
	if (!playlistId || typeof playlistId !== "string") {
		return {
			success: false,
			message: "ID de la playlist invalide"
		};
	}

	try {
		const result = await ApiHelper.get(`/playlists/${playlistId}`);
		return {
			success: true,
			data: result.data
		};
	} catch (error) {
		console.error(
			"Error in getPlaylistById:",
			(error as any).response?.data || (error as any).message
		);
		return {
			success: false,
			message:
				(error as any).message ||
				"Erreur lors de la récupération de la playlist"
		};
	}
}

/**
 * Deletes a media item from a playlist.
 * @param playlistId Playlist identifier
 * @param mediaId Media item identifier
 * @returns Operation result with success status and message
 */
export async function deleteMediaFromPlaylist(
	playlistId: string,
	mediaId: number
) {
	if (!playlistId || typeof playlistId !== "string") {
		return {
			success: false,
			message: "ID de la playlist invalide"
		};
	}

	if (!mediaId || typeof mediaId !== "number") {
		return {
			success: false,
			message: "ID du média invalide"
		};
	}

	try {
		await ApiHelper.delete(`/playlists/${playlistId}/media/${mediaId}`);
		return {
			success: true,
			message: "Média supprimé de la playlist avec succès"
		};
	} catch (error) {
		console.error(
			"Error in deleteMediaFromPlaylist:",
			(error as any).response?.data || (error as any).message
		);
		return {
			success: false,
			message:
				(error as any).message ||
				"Erreur lors de la suppression du média de la playlist"
		};
	}
}

export async function getMovieRuntime(playlistId: string) {
	try {
		const result = await ApiHelper.get(`/playlists/${playlistId}/runtime`);
		console.log("getMovieRuntime result:", result);
		return {
			success: true,
			data: result.data
		};
	} catch (error) {
		console.error(
			"Error in getMovieRuntime:",
			(error as any).response?.data || (error as any).message
		);
		return {
			success: false,
			message:
				(error as any).message ||
				"Erreur lors de la récupération de la playlist"
		};
	}
}
